import { DesignProject } from "@/lib/types";

export const designProjects: DesignProject[] = [
  {
    id: "cloud-made-simple",
    title: "Cloud Made Simple",
    category: "branding",
    tools: ["Canva"],
    thumbnail: {
      src: "/projects/Cloud%20Made%20Simple.%20(1).png",
      alt: "Cloud Made Simple campaign creative",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/Cloudea%20social.png",
        alt: "Cloudea social media design",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Business%20plan%20cover.png",
        alt: "Business plan cover design",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Grainshare%20Logo.png",
        alt: "Grainshare logo design",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Welcome%20to%20Your%20Digital%20Growth%20Partner%20(1).png",
        alt: "Digital growth partner campaign visual",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Create clear and engaging branded visuals for cloud and digital growth messaging.",
    process: "Developed multiple social-first compositions in Canva with consistent layout, contrast, and typography.",
    outcome: "Produced a cohesive branding set that communicates value quickly across social channels.",
    featured: true,
  },
  {
    id: "sacco-management-ui",
    title: "Sacco Management System UI",
    category: "ui",
    tools: ["React", "TypeScript", "Tailwind CSS"],
    thumbnail: {
      src: "/projects/sacco-management-screenshot.png",
      alt: "Sacco Management dashboard interface",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/sacco-management-screenshot.png",
        alt: "Dashboard and member management screens",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Design a comprehensive, fully responsive UI for managing SACCO operations including members, loans, and contributions.",
    process: "Built typed React components and responsive dashboard patterns for data-heavy financial workflows.",
    outcome: "Delivered a production-ready interface with analytics, workflows, and consistent UI behavior.",
    externalLink: "https://sharon404.github.io/Sacco-Management-System/",
    featured: true,
  },
  {
    id: "agriculture-social-pack",
    title: "Agriculture Social Pack",
    category: "social",
    tools: ["Canva"],
    thumbnail: {
      src: "/projects/Green%20and%20White%20Modern%20Agriculture%20Instagram%20Post.png",
      alt: "Modern agriculture Instagram post design",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/Green%20and%20White%20Simple%20Vegetarian%20Day%20Instagram%20Post.png",
        alt: "Vegetarian day social media post",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/6Rs%20for%20conservation.png",
        alt: "6Rs for conservation social post",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/be%20the%20voice%20of%20the%20planet.jpg",
        alt: "Be the voice of the planet social graphic",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/did%20you%20know.jpg",
        alt: "Did you know conservation social card",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Fun%20Fact%20About%20Elephants%20Instagram%20Post.png",
        alt: "Fun fact about elephants social post",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/seeds%20of%20change.jpg",
        alt: "Seeds of change campaign visual",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Swali%20La%20Leo.png",
        alt: "Swali La Leo visual variation one",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Swali%20La%20Leo%20(1).png",
        alt: "Swali La Leo visual variation two",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Swali%20La%20Leo%20(2).png",
        alt: "Swali La Leo visual variation three",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/swali%20la%20leo%20conservation.png",
        alt: "Swali la leo conservation variant",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/swali%20la%20leo%20rabbit.png",
        alt: "Swali la leo rabbit variant",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Swali%20la%20leo%20recycling.jpg",
        alt: "Swali la leo recycling variant",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Unbeatable%20Prices%20Today.png",
        alt: "Unbeatable Prices Today promotional social graphic",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Create scroll-stopping social designs for agriculture and daily engagement themes.",
    process: "Produced template-driven concepts with varied hierarchy and color combinations for repeat campaigns.",
    outcome: "Delivered reusable social assets that support frequent posting without losing visual consistency.",
    featured: true,
  },
  {
    id: "print-campaign-designs",
    title: "Print and Poster Campaign Designs",
    category: "print",
    tools: ["Canva"],
    thumbnail: {
      src: "/projects/Mzima%20flyer.png",
      alt: "Mzima flyer layout",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/Mzima%20Banner.png",
        alt: "Mzima banner design",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Black%20and%20White%20Mother's%20Day%20Card.png",
        alt: "Black and white mothers day card design",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/Purple%20Watercolor%20Happy%20Mother's%20Day%20Poster.png",
        alt: "Purple watercolor mothers day poster",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Build clear print-ready visuals for events, campaigns, and greetings.",
    process: "Balanced typography, spacing, and hierarchy for formats suited to both print and digital reposts.",
    outcome: "Produced polished poster and flyer assets with clear messaging and strong visual identity.",
    featured: false,
  },
  {
    id: "motion-gif-design",
    title: "Animation Concepts",
    category: "motion",
    tools: ["Canva"],
    thumbnail: {
      src: "/projects/Animation.gif",
      alt: "Animated motion concept preview",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/Animation.gif",
        alt: "Animated concept frame sequence",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Create lightweight animated content suitable for social storytelling.",
    process: "Developed motion timing and transitions optimized for short-view attention spans.",
    outcome: "Delivered reusable animation concepts that complement video and static campaign assets.",
    featured: false,
  },
  {
    id: "ui-project-previews",
    title: "Grainshare Product Preview",
    category: "ui",
    tools: ["Web Design"],
    thumbnail: {
      src: "/projects/grainshare-screenshot.png",
      alt: "Grainshare website preview",
      width: 1200,
      height: 800,
    },
    gallery: [
      {
        src: "/projects/grainshare-screenshot.png",
        alt: "Grainshare landing page visual",
        width: 1200,
        height: 800,
      },
      {
        src: "/projects/tutorial-app-screenshot.png",
        alt: "Tutorial app dashboard preview",
        width: 1200,
        height: 800,
      },
    ],
    challenge: "Present clear product interfaces for portfolio-ready project communication.",
    process: "Captured and curated high-clarity screenshots to represent production UI quality.",
    outcome: "Added clean UI previews that improve first-glance understanding of product direction.",
    featured: false,
  },
];
